import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import ClientWrapper from "./ClientWrapper";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sri Lanka Orthopaedic Association",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-x-hidden relative`}
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <div className="max-w-[1560px] mx-auto">
            <ClientWrapper>
              <Navbar />
              {children}
              <Footer />
            </ClientWrapper>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
